# Generated by Django 3.1.2 on 2020-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201029_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.IntegerField(blank=True, error_messages={'unique': 'A user with that employee_id already exists.'}, null=True, unique=True, verbose_name='社員ID'),
        ),
    ]
