# Generated by Django 3.1.2 on 2020-10-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_attendance_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_id',
            new_name='user',
        ),
    ]
