# Generated by Django 3.1.2 on 2020-10-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_auto_20201024_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='user_id',
        ),
    ]
