# Generated by Django 3.1.2 on 2020-10-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_auto_20201025_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_id',
            new_name='user',
        ),
    ]
