# Generated by Django 3.1.2 on 2020-10-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_auto_20201025_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_id',
        ),
    ]
