# Generated by Django 3.1.2 on 2020-11-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0010_auto_20201026_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_id',
            new_name='employee_id',
        ),
    ]
