# Generated by Django 3.1.2 on 2020-11-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0011_auto_20201103_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.IntegerField(verbose_name='社員ID'),
        ),
    ]
